### ISSUE TITLE
一点疑问

### ISSUE THREAD

**Issue by budaLi** [LaiSongxuan/SynSig2Vec#1]
您好，非常感谢您的开源。
初步阅读了您的paper(The SynSig2Vec method [1,2] for dynamic signature synthesis and verification. )及一篇相关的专利(一种基于样本合成以及排序学习的联机签名鉴定方法）。根据我的拙略理解，本质就是基于Sigma Lognormal理论构造了拟合笔迹运动的一个函数，利用先验知识增加了部分扰动，可以对每个用户的每个真实签名生成多个真实签名和伪造签名，然后将得到的Vx,Vy,Vxy作为神经网络的输入，去构造了512维的特征作为笔迹的特征，然后测试时用模型得到特征值然后去计算相似度，是这样去做的笔迹识别对嘛。
期待您的答复。

**Comment by LaiSongxuan** [comment]
您好，感谢对我们工作的关注。您的理解是对的，基于先验知识构造真伪样本，然后网络去学习区分这些样本。

**Comment by budaLi** [comment]
感谢您的回复。
在结合代码阅读您的论文后有个大家应该都能想到的点，把数据集中原本的负样本也增加进去是否对于最终的结果有影响呢，大概是您的论文创新点就是基于Sigma Lognormal理论去生成特征所以不太好去用原本就有的负样本，还是您这边测试之后发现意义不大。
另外就是关于Sigma Lognormal的代码实现部分...看起来像是学术派代码风格，有点晦涩...

**Comment by LaiSongxuan** [comment]
你好，之所以不考虑这种设置，主要是因为论文出发点是forgery-free training，也就是伪造样本不存在情况下如何有效地进行模型训练。Sigma lognormal算法逻辑主要参考Development of a Sigma–Lognormal representation for on-line signatures，至于具体实现，确实没有很好地进行工程上的优化...主要思路就是滑窗法检测局部波峰，然后进行lognormal拟合。

**Comment by budaLi** [comment]
花了一段时间debug您的代码，有个关于loss的疑问，我的理解是您把一个user当成一个batch，里面依次拼接了anchor, positive,negative， label值是这个user的id索引，loss中用的是分类的交叉熵，默认把一个batch里的所有数据都当成一个id去进行分类，这样的话不是会造成负样本也会被当成正样本去反向传播嘛...

**Comment by LaiSongxuan** [comment]
是的，分类支路是对字形或者内容进行分类，不区分真伪。例如，真伪的“小明”都分为同一类。
